<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pulgapp.Server.Infrastructure\Pulgapp.Server.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Pulgapp.Server.Core\Pulgapp.Server.Core.csproj" />
    <ProjectReference Include="..\..\src\Pulgapp.Server.Protocol\Pulgapp.Server.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
  </ItemGroup>

</Project>
